// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.Database.Entity;

namespace Services.Migrations
{
    [DbContext(typeof(GameWebDbContext))]
    partial class GameWebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Services.Database.Model.UserBasic", b =>
                {
                    b.Property<Guid>("Gid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("Career");

                    b.Property<string>("County");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Education");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<int>("Enable");

                    b.Property<string>("HashedPassword")
                        .IsRequired();

                    b.Property<string>("Hospital");

                    b.Property<string>("Income");

                    b.Property<string>("LineId")
                        .HasMaxLength(50);

                    b.Property<string>("Mobile")
                        .HasMaxLength(20);

                    b.Property<string>("NickName")
                        .HasMaxLength(20);

                    b.Property<int>("Role");

                    b.Property<int>("Sex");

                    b.Property<string>("Sexual");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Gid");

                    b.ToTable("UserBasic");
                });
#pragma warning restore 612, 618
        }
    }
}
